namespace UnderWarden.Logic.Knowledge;

/// <summary>
/// Pure data record for the monster inspect UI. All fields except Name and Tier may be null,
/// meaning "not yet revealed at the current knowledge tier." The UI renders null fields as
/// hidden/redacted — never as "0" or empty string.
///
/// This is the single source of truth for what the UI displays.
/// Generated by MonsterKnowledgeSystem.GetInfoView — UI code should consume this, not raw stats.
/// </summary>
public sealed record MonsterInfoView(
    string Name,
    KnowledgeTier Tier,

    /// <summary>Faction label (Tier 1+). E.g. "Orc Warband", "Undead".</summary>
    string? FactionLabel,

    /// <summary>Role label derived from tags/name (Tier 1+). E.g. "Brute", "Swarm".</summary>
    string? RoleLabel,

    /// <summary>Speed bucket (Tier 1+). One of: "Sluggish", "Normal", "Fast", "Lightning Fast".</summary>
    string? SpeedLabel,

    /// <summary>Durability bucket (Tier 2+). One of: "Fragile", "Sturdy", "Very Tough", "Monstrous".</summary>
    string? DurabilityLabel,

    /// <summary>Damage bucket (Tier 2+). One of: "Light", "Moderate", "Heavy", "Brutal".</summary>
    string? DamageLabel,

    /// <summary>Accuracy bucket (Tier 2+). One of: "Often Misses", "Usually Hits", "Rarely Misses".</summary>
    string? AccuracyLabel,

    /// <summary>Evasion bucket (Tier 2+). One of: "Easy to Hit", "Average Evasion", "Hard to Hit".</summary>
    string? EvasionLabel,

    /// <summary>Warning strings about dangerous traits (Tier 3+). E.g. "Carries the Plague of Restless Death".</summary>
    IReadOnlyList<string> SpecialWarnings,

    /// <summary>Short tactical advice string (Tier 3+). Null if no specific advice available.</summary>
    string? AdviceLine
);
