using System.Text.Json.Serialization;

namespace UnderWarden.Logic.Persistence.MidRun;

/// <summary>
/// Source-generated JSON context for the mid-run entity/component serializer. Required for iOS
/// NativeAOT (reflection-based serialization is unsafe there) and it is what keeps the hot path
/// reflection-free — every DTO is registered here so the generator emits its serializer, and the
/// registry references the generated JsonTypeInfo per type.
/// </summary>
[JsonSourceGenerationOptions(WriteIndented = false)]
// roots
[JsonSerializable(typeof(EntityTableDto))]
[JsonSerializable(typeof(EntityRecord))]
[JsonSerializable(typeof(ComponentEnvelope))]
// shared value DTOs
[JsonSerializable(typeof(PointDto))]
[JsonSerializable(typeof(MonsterAbilityDto))]
[JsonSerializable(typeof(TrapActionDto))]
[JsonSerializable(typeof(TrapPayloadDto))]
[JsonSerializable(typeof(EmptyDto))]
// Balance
[JsonSerializable(typeof(ThreatArchetypeTagDto))]
// Combat
[JsonSerializable(typeof(ConsumableDto))]
[JsonSerializable(typeof(DamageModifiersDto))]
[JsonSerializable(typeof(EquipmentDto))]
[JsonSerializable(typeof(EquippableDto))]
[JsonSerializable(typeof(FighterDto))]
[JsonSerializable(typeof(PortalComponentDto))]
[JsonSerializable(typeof(SpeedBonusTrackerDto))]
[JsonSerializable(typeof(SpellEffectDto))]
[JsonSerializable(typeof(WandComponentDto))]
// Combat.StatusEffects
[JsonSerializable(typeof(StatusTurnsDto))]
[JsonSerializable(typeof(AggravatedEffectDto))]
[JsonSerializable(typeof(BarkskinEffectDto))]
[JsonSerializable(typeof(BleedEffectDto))]
[JsonSerializable(typeof(BlindedEffectDto))]
[JsonSerializable(typeof(BurningEffectDto))]
[JsonSerializable(typeof(CrippledEffectDto))]
[JsonSerializable(typeof(DissonantChantEffectDto))]
[JsonSerializable(typeof(EnragedEffectDto))]
[JsonSerializable(typeof(FocusedEffectDto))]
[JsonSerializable(typeof(HeroismEffectDto))]
[JsonSerializable(typeof(PlagueEffectDto))]
[JsonSerializable(typeof(PoisonEffectDto))]
[JsonSerializable(typeof(PossessionEffectDto))]
[JsonSerializable(typeof(ProtectionEffectDto))]
[JsonSerializable(typeof(RallyEffectDto))]
[JsonSerializable(typeof(RegenerationEffectDto))]
[JsonSerializable(typeof(ShieldEffectDto))]
[JsonSerializable(typeof(SluggishEffectDto))]
[JsonSerializable(typeof(SpeedEffectDto))]
[JsonSerializable(typeof(TauntedEffectDto))]
[JsonSerializable(typeof(WeaknessEffectDto))]
// ECS
[JsonSerializable(typeof(AiComponentDto))]
[JsonSerializable(typeof(AlertedStateDto))]
[JsonSerializable(typeof(AutoExploreStateDto))]
[JsonSerializable(typeof(ChestComponentDto))]
[JsonSerializable(typeof(ChestLootStashDto))]
[JsonSerializable(typeof(CorpseComponentDto))]
[JsonSerializable(typeof(CorrosionComponentDto))]
[JsonSerializable(typeof(DestructiblePropComponentDto))]
[JsonSerializable(typeof(FloorTrapComponentDto))]
[JsonSerializable(typeof(HostAbilityComponentDto))]
[JsonSerializable(typeof(IdentifiableItemDto))]
[JsonSerializable(typeof(InnateRegenComponentDto))]
[JsonSerializable(typeof(InventoryDto))]
[JsonSerializable(typeof(ItemTagDto))]
[JsonSerializable(typeof(KeyItemComponentDto))]
[JsonSerializable(typeof(LichAiComponentDto))]
[JsonSerializable(typeof(LifeDrainComponentDto))]
[JsonSerializable(typeof(LockableComponentDto))]
[JsonSerializable(typeof(MuralComponentDto))]
[JsonSerializable(typeof(NecromancerAiComponentDto))]
[JsonSerializable(typeof(OnHitEffectComponentDto))]
[JsonSerializable(typeof(OrcChieftainComponentDto))]
[JsonSerializable(typeof(OrcShamanComponentDto))]
[JsonSerializable(typeof(PortalCastStateComponentDto))]
[JsonSerializable(typeof(RaisedFromCorpseTagDto))]
[JsonSerializable(typeof(RingEffectComponentDto))]
[JsonSerializable(typeof(RunAggressionTallyDto))]
[JsonSerializable(typeof(KillEntryDto))]
[JsonSerializable(typeof(ShieldWallComponentDto))]
[JsonSerializable(typeof(SignpostComponentDto))]
[JsonSerializable(typeof(SkirmisherComponentDto))]
[JsonSerializable(typeof(SpeciesTagDto))]
[JsonSerializable(typeof(SplitTrackerDto))]
[JsonSerializable(typeof(StairDto))]
[JsonSerializable(typeof(StatusImmunityComponentDto))]
[JsonSerializable(typeof(TrapPayloadComponentDto))]
[JsonSerializable(typeof(WeaponAcidCoatingComponentDto))]
public partial class MidRunJsonContext : JsonSerializerContext { }
